const NORFOLK_LOCATIONS = [
  // City
  "Norwich",

  // Towns
  "Acle",
  "Attleborough",
  "Aylsham",
  "Cromer",
  "Dereham",
  "Diss",
  "Downham Market",
  "Fakenham",
  "Gorleston-on-Sea",
  "Great Yarmouth",
  "Harleston",
  "Hingham",
  "Holt",
  "Hunstanton",
  "King's Lynn",
  "Loddon",
  "North Walsham",
  "Reepham",
  "Sheringham",
  "Stalham",
  "Swaffham",
  "Thetford",
  "Thorpe St Andrew",
  "Watton",
  "Wells-next-the-Sea",
  "Wymondham",

  // Villages
  "Alburgh", "Alby", "Aldborough", "Aldeby", "Alderford", "Alpington", "Anmer", "Antingham", "Arminghall", "Ashby St Mary", "Ashill", "Ashmanhaugh", "Ashwellthorpe", "Ashwicken", "Aslacton", "Attlebridge", "Aylmerton",
  "Babingley", "Baconsthorpe", "Bacton", "Bagthorpe", "Bale", "Banham", "Banningham", "Barford", "Barney", "Barnham Broom", "Barton Bendish", "Barton Turf", "Bawburgh", "Bawdeswell", "Bawsey", "Beachamwell", "Beeston Regis", "Belaugh", "Bergh Apton", "Bessingham", "Besthorpe", "Billingford", "Binham", "Bintree", "Blakeney", "Blickling", "Blofield", "Bodham", "Booton", "Bracon Ash", "Bradenham", "Bramerton", "Brampton", "Brancaster", "Brandiston", "Bressingham", "Briston", "Brockdish", "Brundall", "Buckenham", "Burgh Castle", "Burgh St Peter", "Burnham Deepdale", "Burnham Market", "Burnham Norton", "Burnham Overy", "Burnham Thorpe", "Burston", "Buxton",
  "Caister-on-Sea", "California", "Cantley", "Carbrooke", "Carleton Rode", "Castle Acre", "Castle Rising", "Caston", "Catfield", "Cawston", "Chedgrave", "Claxton", "Clenchwarton", "Cley next the Sea", "Clint Green", "Clippesby", "Cockley Cley", "Colkirk", "Colney", "Coltishall", "Congham", "Corpusty", "Costessey", "Cranworth", "Cringleford", "Crostwick", "Crostwight", "Crownthorpe",
  "Denton", "Denver", "Deopham", "Dersingham", "Dickleburgh", "Dilham", "Ditchingham", "Docking", "Drayton", "Dunston", "Dunton",
  "Earsham", "East Barsham", "East Carleton", "East Harling", "East Rudham", "East Ruston", "East Tuddenham", "East Winch", "Easton", "Eccles on Sea", "Edgefield", "Edingthorpe", "Elsing", "Erpingham",
  "Felbrigg", "Felthorpe", "Feltwell", "Fersfield", "Field Dalling", "Filby", "Fincham", "Fleggburgh", "Flitcham", "Flordon", "Forncett", "Foulden", "Foulsham", "Foxley", "Framingham Earl", "Framingham Pigot", "Freethorpe", "Frettenham",
  "Garboldisham", "Garvestone", "Gateley", "Gayton", "Gaywood", "Gillingham", "Gimingham", "Gissing", "Glandford", "Gooderstone", "Great Bircham", "Great Cressingham", "Great Dunham", "Great Ellingham", "Great Massingham", "Great Plumstead", "Great Ryburgh", "Great Snoring", "Gressenhall", "Grimston", "Griston", "Guestwick", "Guist",
  "Hackford", "Haddiscoe", "Hainford", "Hales", "Halvergate", "Hanworth", "Happisburgh", "Hapton", "Hardingham", "Hardwick", "Harpley", "Hassingham", "Haveringland", "Heacham", "Heckingham", "Hedenham", "Hellesdon", "Hemblington", "Hempnall", "Hempstead", "Hempton", "Hemsby", "Hethersett", "Hevingham", "Heydon", "Hickling", "Hilborough", "Hilgay", "Hillington", "Hindolveston", "Hindringham", "Hockering", "Hockwold cum Wilton", "Hoe", "Holkham", "Holme Hale", "Holme-next-the-Sea", "Honing", "Honingham", "Horning", "Horsey", "Horsford", "Horsham St Faith", "Horstead", "Houghton", "Hoveton", "Howe",
  "Ickburgh", "Illington", "Ingham", "Ingoldisthorpe", "Ingworth", "Intwood", "Irstead", "Itteringham",
  "Kelling", "Kempstone", "Kenninghall", "Keswick", "Ketteringham", "Kettlestone", "Kimberley", "Kirby Bedon", "Kirby Cane", "Kirstead", "Knapton",
  "Lamas", "Langham", "Larling", "Lenwade", "Letheringsett", "Leziate", "Limpenhoe", "Lingwood", "Litcham", "Little Barningham", "Little Cressingham", "Little Ellingham", "Little Massingham", "Little Plumstead", "Little Snoring", "Long Stratton", "Ludham", "Lyng",
  "Marham", "Marlingford", "Marsham", "Martham", "Matlask", "Mattishall", "Mautby", "Melton Constable", "Methwold", "Middleton", "Mileham", "Morley St Botolph", "Morningthorpe", "Morston", "Morton on the Hill", "Moulton St Mary", "Mulbarton", "Mundesley", "Mundford",
  "Narborough", "Narford", "Neatishead", "Necton", "Needham", "New Buckenham", "Newton Flotman", "Nordelph", "North Creake", "North Elmham", "North Pickenham", "North Runcton", "North Tuddenham", "Northwold", "Norton Subcourse",
  "Oby", "Old Buckenham", "Old Catton", "Old Hunstanton", "Ormesby St Margaret", "Ormesby St Michael", "Oulton", "Outwell", "Overstrand", "Ovington", "Oxborough",
  "Palgrave", "Panxworth", "Paston", "Pentney", "Plumstead", "Poringland", "Postwick", "Potter Heigham", "Pudding Norton", "Pulham Market", "Pulham St Mary",
  "Quidenham",
  "Rackheath", "Ranworth", "Raveningham", "Reedham", "Repps", "Reymerston", "Ringland", "Ringstead", "Rockland All Saints", "Rockland St Mary", "Rockland St Peter", "Rollesby", "Roudham", "Rougham", "Roughton", "Roydon", "Runcton Holme", "Runhall", "Runham", "Rushall", "Rushford",
  "Saham Toney", "Salhouse", "Salle", "Salthouse", "Sandringham", "Saxlingham Nethergate", "Saxthorpe", "Scarning", "Scole", "Scottow", "Scoulton", "Sculthorpe", "Sea Palling", "Sedgeford", "Seething", "Setchey", "Sharrington", "Shelfanger", "Shelton", "Shereford", "Shernborne", "Shimpling", "Shingham", "Shipdham", "Shotesham", "Shouldham", "Shropham", "Sidestrand", "Sisland", "Skeyton", "Sloley", "Smallburgh", "Snetterton", "Snettisham", "Somerton", "South Acre", "South Creake", "South Pickenham", "South Raynham", "South Walsham", "Southwood", "Sparham", "Spixworth", "Sporle", "Sprowston", "Stacksford", "Stibbard", "Stiffkey", "Stockton", "Stody", "Stoke Holy Cross", "Stokesby", "Stow Bedon", "Stradsett", "Stratton Strawless", "Strumpshaw", "Surlingham", "Sustead", "Sutton", "Swafield", "Swainsthorpe", "Swannington", "Swanton Abbott", "Swanton Morley", "Swanton Novers", "Swardeston", "Syderstone",
  "Tacolneston", "Tasburgh", "Tattersett", "Taverham", "Terrington St Clement", "Terrington St John", "Tharston", "Themelthorpe", "Thompson", "Thornage", "Thornham", "Thorpe Market", "Threxton", "Thrigby", "Thurgarton", "Thurlton", "Thurning", "Thursford", "Thurton", "Thwaite", "Tibenham", "Tilney All Saints", "Tilney St Lawrence", "Tittleshall", "Tivetshall St Margaret", "Tivetshall St Mary", "Toft Monks", "Toftwood", "Topcroft", "Tottenhill", "Trimingham", "Trowse", "Trunch", "Tunstall", "Tunstead", "Tuttington", "Twyford",
  "Upper Sheringham", "Upton", "Upwell",
  "Wacton", "Walcott", "Walpole Cross Keys", "Walpole Highway", "Walpole St Andrew", "Walpole St Peter", "Walsingham", "Walsoken", "Warham", "Watlington", "Waxham", "Weasenham All Saints", "Weasenham St Peter", "Weeting", "Welborne", "Wellingham", "Welney", "Wendling", "Wereham", "West Acre", "West Barsham", "West Beckham", "West Bilney", "West Bradenham", "West Dereham", "West Lexham", "West Lynn", "West Newton", "West Raynham", "West Rudham", "West Runton", "West Somerton", "West Walton", "West Winch", "Westfield", "Weston Longville", "Westwick", "Weybourne", "Wheatacre", "Whinburgh", "Whissonsett", "Wickhampton", "Wicklewood", "Wickmere", "Wiggenhall St Germans", "Wiggenhall St Mary Magdalen", "Wighton", "Wimbotsham", "Winfarthing", "Winterton-on-Sea", "Witton", "Wiveton", "Wood Dalling", "Wood Norton", "Woodbastwick", "Woodton", "Wormegay", "Worstead", "Wramplingham", "Wreningham", "Wretham", "Wretton", "Wroxham",
  "Yaxham", "Yelverton",
];

export const UNIQUE_UK_LOCATIONS = Array.from(new Set(NORFOLK_LOCATIONS)).sort();
