export const MOCK_PROPERTIES = [
  {
    id: '1',
    title: 'Beautiful 3 Bed Semi-Detached House',
    address: '12 Riverside Road, Norwich, NR1',
    price: 350000,
    bedrooms: 3,
    bathrooms: 2,
    description: 'A stunning 3 bedroom family home located close to the city centre.\n\nFeaturing a large rear garden, modern fitted kitchen, and spacious living areas. Perfect for a growing family or professionals looking for easy access to central Norwich and the train station.',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop'],
    location: { lat: 52.628, lng: 1.305 },
    isBoosted: true,
    agent: { name: 'Norfolk Estates', logo: 'https://ui-avatars.com/api/?name=NE&background=0D8ABC&color=fff' }
  },
  {
    id: '2',
    title: 'Modern 2 Bed Apartment',
    address: '45 Unthank Road, Norwich, NR2',
    price: 275000,
    bedrooms: 2,
    bathrooms: 1,
    description: 'High spec apartment in the highly sought-after Golden Triangle.\n\nOpen plan living space, large bay windows, and secure parking. Ideal for a first-time buyer wanting to be close to local cafes and pubs.',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop'],
    location: { lat: 52.622, lng: 1.285 },
    isBoosted: false,
    agent: { name: 'City Living', logo: 'https://ui-avatars.com/api/?name=CL&background=F39C12&color=fff' }
  },
  {
    id: '3',
    title: 'Spacious 4 Bed Detached Family Home',
    address: '88 Newmarket Road, Norwich, NR2',
    price: 600000,
    bedrooms: 4,
    bathrooms: 3,
    description: 'Large garden, driveway, perfect for families.\n\nRecently renovated throughout. Includes an en-suite master bedroom, utility room, and a beautifully landscaped south-facing garden. Walking distance to top local schools.',
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop'],
    location: { lat: 52.618, lng: 1.280 },
    isBoosted: true,
    agent: { name: 'Norfolk Estates', logo: 'https://ui-avatars.com/api/?name=NE&background=0D8ABC&color=fff' }
  },
  {
    id: '4',
    title: 'Cozy 1 Bed Studio',
    address: '22 Tombland, Norwich, NR3',
    price: 180000,
    bedrooms: 1,
    bathrooms: 1,
    description: 'Perfect for young professionals.\n\nLocated right in the heart of Norwich, opposite the Cathedral. Features exposed beams, modern kitchen, and unbeatable access to city life.',
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format&fit=crop'],
    location: { lat: 52.631, lng: 1.300 },
    isBoosted: false,
    agent: { name: 'Urban Spaces', logo: 'https://ui-avatars.com/api/?name=US&background=2C3E50&color=fff' }
  },
  {
    id: '5',
    title: 'Executive 5 Bed Detached Residence',
    address: '15 Eaton Road, Norwich, NR4',
    price: 825000,
    bedrooms: 5,
    bathrooms: 4,
    description: 'A magnificent executive home in one of Norwich\'s most prestigious addresses.\n\nBoasting over 3000 sq ft of living space, a double garage, and a stunning open-plan kitchen/diner. The master suite features a walk-in wardrobe and full en-suite.',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop'],
    location: { lat: 52.608, lng: 1.265 },
    isBoosted: true,
    agent: { name: 'Norfolk Estates', logo: 'https://ui-avatars.com/api/?name=NE&background=0D8ABC&color=fff' }
  },
  {
    id: '6',
    title: 'Charming 3 Bed Terrace near UEA',
    address: '102 Bluebell Road, Norwich, NR5',
    price: 240000,
    bedrooms: 3,
    bathrooms: 1,
    description: 'Perfect for investors or first-time buyers.\n\nIdeally located for the University of East Anglia and the Norfolk & Norwich Hospital. This well-presented terrace offers three good-sized bedrooms and a private rear garden.',
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop'],
    location: { lat: 52.615, lng: 1.255 },
    isBoosted: false,
    agent: { name: 'City Living', logo: 'https://ui-avatars.com/api/?name=CL&background=F39C12&color=fff' }
  },
  {
    id: '7',
    title: 'Riverside 4 Bed Detached House',
    address: '54 Yarmouth Road, Norwich, NR7',
    price: 575000,
    bedrooms: 4,
    bathrooms: 2,
    description: 'Stunning riverside views in Thorpe St Andrew.\n\nThis beautiful family home features a private mooring, large riverside garden, and balcony overlooking the Yare. Recently updated with a contemporary feel throughout.',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop'],
    location: { lat: 52.625, lng: 1.335 },
    isBoosted: true,
    agent: { name: 'Norfolk Estates', logo: 'https://ui-avatars.com/api/?name=NE&background=0D8ABC&color=fff' }
  },
  {
    id: '8',
    title: 'Immaculate 3 Bed Bungalow',
    address: '22 School Road, Norwich, NR8',
    price: 340000,
    bedrooms: 3,
    bathrooms: 2,
    description: 'Spacious and well-maintained bungalow in popular Drayton.\n\nOffered with no onward chain, this property features a large conservatory, modern shower room, and a beautifully landscaped rear garden. Ample off-road parking.',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop'],
    location: { lat: 52.668, lng: 1.225 },
    isBoosted: false,
    agent: { name: 'Urban Spaces', logo: 'https://ui-avatars.com/api/?name=US&background=2C3E50&color=fff' }
  }
];
